### ISSUE TITLE
Add definition to the card numbers

### ISSUE THREAD

**Issue by andrew-fleming** [dustinstacy/triple-triad#20]
The card numbers seem a bit difficult to read. I propose adding further definition to them or changing the font

**Comment by dustinstacy** [comment]
Appreciate the feedback!

Clarity will certainly be a point of emphasis on future iterations. 

In the mean time, might I inquire the device and resolution you are experiencing this issue on? My intuition leans towards it being a media query issue as I've calibrated based on the devices I currently use.

**Comment by andrew-fleming** [comment]
Excellent to hear!

I ran this on a 16' MacBook pro: 3072‑by‑1920 native resolution at 226 ppi

I'm not sure how much this will help, but I'll include a screenshot for reference. The number issue is really for the cards that haven't been played. I can tell what the numbers are, but they just appear a bit blurry. Once the card pops up and is on the board, they're much more clear.
![Screen Shot 2022-11-18 at 11 49 29 PM](https://user-images.githubusercontent.com/69282788/202835005-0dc1f5a9-510a-4ca4-9a70-5e1d9c007c7e.png)

**Comment by dustinstacy** [comment]
Thank you for the details and screenshot! I'll need to be explicit about requesting this format in future bug/design inquiries (or create a form).

I was looking to identify any possible break points in the responsiveness, but your display falls well withing the confines of the query parameters. It's now certain though that we are on the same page as to the issue we are identifying.

 I'm glad you sparked this conversation as this is a huge design decision and one that will play a heavier role when we include more information on the cards. Seems to be a common pain point for most CCG games especially when scaling down to mobile displays. Some possible fixes include:
- layering the cards over one another and pulling the selected to the forefront (original design in FFVIII)
- creating a card wheel (which would help on mobile)
- sliding screen based on player turn. (would help to maximize space on all aspect ratios)
- refining font family and definition (as you mentioned!)

Long winded way of saying it will be remedied! There remains a possibility that this repo will see some improvements in relation to this issue, but with focus on the new iteration, this will be more of a playground for testing component features. It will remain functional, but should something fit nicely into place here, I'll gladly port it over!
